# These are supported funding model platforms

github: melans
custom: ['https://www.paypal.com/paypalme/anssary', 'https://www.paypal.com/donate/?business=anssary@googlemail.com&currency_code=USD&item_name=Support+Islamic+Prayer+Times+Visualization']
